### ISSUE TITLE
iNeed Window not displaying properly.

### ISSUE THREAD

**Issue by ffwrude** [opussf/INeed#16]
Hello.

I am using this wonderfull addon for a long time and just found its github. So the iNeed little window started to function for some reason yesterday (i had never seen it work before) and it's very nice.

But it tends to disapear when reloading and not populating with items that are already in the list.
(I'm on version 0.21 btw but used to be on 0.19 as it was the last one available on curse before wowup and curse divorce)

**Comment by opussf** [comment]
Hi!

First, thank you very much for the nice note.  Always good to hear from those who use my addons.

I'm also interested to find out what the expected behavior for the window is.  This may lead to some options, or expanded functionality.  It currently is setup to only show the most recently updated items for 5 minutes, sorted most recent down.  

By reloading, you mean:  window is displayed, /reload, no window?  I'll look into that.

Thank you very much for your feedback.   I hope to do some work on this soon.

**Comment by ffwrude** [comment]
Hello,

It’s a wonderfull addon !

/reload doesn’t make it go away.

I think i would love to have it an option « 5  minutes » or « all the time » ? Something like this ? it is the BEST addon for this kind of thing. Way better than titan farm buddy

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :jeudi 4 août 2022 09:59
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


Hi!

First, thank you very much for the nice note. Always good to hear from those who use my addons.

I'm also interested to find out what the expected behavior for the window is. This may lead to some options, or expanded functionality. It currently is setup to only show the most recently updated items for 5 minutes, sorted most recent down.

By reloading, you mean: window is displayed, /reload, no window? I'll look into that.

Thank you very much for your feedback. I hope to do some work on this soon.

**Comment by ffwrude** [comment]
Oh,

Note too. Sometime you have a list that is more than one or two items. When you disconnect and reconnect, you will not have the window and when you loot one item in your list, it will only show one line (the item you juste got).

Example

/in linen cloth 10
/in wool cloth 10

If the window disepear. You will only see linen cloth when you loot Something and you will not got wool cloth before you loot one again.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :jeudi 4 août 2022 09:59
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


Hi!

First, thank you very much for the nice note. Always good to hear from those who use my addons.

I'm also interested to find out what the expected behavior for the window is. This may lead to some options, or expanded functionality. It currently is setup to only show the most recently updated items for 5 minutes, sorted most recent down.

By reloading, you mean: window is displayed, /reload, no window? I'll look into that.

Thank you very much for your feedback. I hope to do some work on this soon.

**Comment by opussf** [comment]
@ffwrude Please try this release:  0.22.0-alpha-3

**Comment by ffwrude** [comment]
Ok so ater a few test what i did was :


  *   I put back 4 items with stacks that i already have in my list which where :
     *   50 arkhana
     *   5 meat stuff
     *   5 other meat stuff
     *   5 eggs stuff
  *   I had ineed display all 4 in the panel (which is good)
  *   Ported to legion, panel stayed.
  *   Then i started Killing things. Got 5 meats. And it worked good. Line disappeared.
  *   But when i looted Something that was previously in my list and not displayed in the panel, i got the arkhana disappearing from the panel.
  *   Maybe it’s because i looted Something that wasn’t displayed and was Added BEFORE updating to the new version ?

Settings like this :

***@***.***

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 28 août 2022 06:36
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


@ffwrude<https://github.com/ffwrude> Please try this release: 0.22.0-alpha-3

**Comment by ffwrude** [comment]
Ok my apology because i answered to you by email and the whole thing you wrote wasn’t displayed.


  *   Oldest command doesn’t work or i don’t understand it. I typed /in oldest and i can’t press enter
  *   Fill bar i don’t really get how it works.
  *   Updated item list works.
  *   Your fourth point i don’t get it
  *   It’s better than version 0.21 for sure.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 28 août 2022 06:36
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


@ffwrude<https://github.com/ffwrude> Please try this release: 0.22.0-alpha-3

**Comment by ffwrude** [comment]
Upon further testing this is the issues i had that are kinda annoying (not much)


  *   Sometime the window disappear for no reason (no reload, no Nothing)
  *   Options seems to not get save sometime.
  *   List doesn’t load at startup.

Other than that it’s pretty neat !

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 28 août 2022 06:36
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


@ffwrude<https://github.com/ffwrude> Please try this release: 0.22.0-alpha-3

**Comment by opussf** [comment]
@ffwrude There are 2 new options in the `/in options` panel that set time durations.  One is for how long to show an item after it has been updated, the 2nd one, with the [x] Fill Items option is how long to show the older items.

**Comment by ffwrude** [comment]
Oh ok...

A tooltip could be a good thing. Thanks you anyway. I am very happy with this addon

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by opussf** [comment]
@ffwrude I've been reading this more.  I think I understand the issue.  Let me re-describe it back to you.

You added 4 items (50 arkhana, meat stuff, other meat stuff, and eggs).  
Then you looted something that was not in the UI display (but in your list) and arkhana vanished from the list.

This, if I understand it, is as it was intended to work.  Let me explain.

Before, an item has 2 timestamps (Added, and updated).  If you add a new item to the list, both are set to the current time. The display would look for items that were updated in the last <n> seconds (default of 5 minutes), and display them.
If the quantity changed (you looted, sold or scrapped something), then the updated time was changed, and it would display.  It it took longer than 5 minutes to loot something, it would 'expire' off of the UI display.

This was to try to keep the UI showing only the most recent items, and if there is a rare item that you are trying to find, it would not constantly bug you about it.

Adding an item that was already added, or changing the needed quantity, also counts as updating the item.  That item would show up in the UI until the update expired.

The recent change I made did 2 things.  The amount of time until an item expires can be set really high.   Also, once items start to expire off of the UI list, and bars are made available, then the oldest items will be displayed for an additional amount of time.  (That is the [ ] Fill Bars and the duration).

Note that the time out for the Fill Bars portion is kept in memory, not based on saved data (except for the duration).

Hope this helps.

**Comment by ffwrude** [comment]
I understand.

I found a workaround to this though, i display 40 lines of iNeed with 999 days. Then it works as i want so all is good for me.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :jeudi 1 septembre 2022 05:03
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


@ffwrude<https://github.com/ffwrude> I've been reading this more. I think I understand the issue. Let me re-describe it back to you.

You added 4 items (50 arkhana, meat stuff, other meat stuff, and eggs).
Then you looted something that was not in the UI display (but in your list) and arkhana vanished from the list.

This, if I understand it, is as it was intended to work. Let me explain.

Before, an item has 2 timestamps (Added, and updated). If you add a new item to the list, both are set to the current time. The display would look for items that were updated in the last seconds (default of 5 minutes), and display them.
If the quantity changed (you looted, sold or scrapped something), then the updated time was changed, and it would display. It it took longer than 5 minutes to loot something, it would 'expire' off of the UI display.

This was to try to keep the UI showing only the most recent items, and if there is a rare item that you are trying to find, it would not constantly bug you about it.

Adding an item that was already added, or changing the needed quantity, also counts as updating the item. That item would show up in the UI until the update expired.

The recent change I made did 2 things. The amount of time until an item expires can be set really high. Also, once items start to expire off of the UI list, and bars are made available, then the oldest items will be displayed for an additional amount of time. (That is the [ ] Fill Bars and the duration).

Note that the time out for the Fill Bars portion is kept in memory, not based on saved data (except for the duration).

Hope this helps.

**Comment by ffwrude** [comment]
Just installed it.

Will tell you if it’s all good after a little usage.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 28 août 2022 06:36
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [opussf/INeed] iNeed Window not displaying properly. (Issue #16)


@ffwrude<https://github.com/ffwrude> Please try this release: 0.22.0-alpha-3
